In [1]:
# n = 10
[1,-1,-1,1]
# predicted return, return volatility over prior year, correlation of stock with CRSP value-weighted index (Mkt-RF), OOS R2
# long only strategy cum return - up to 2020
# sharpe ratio is (monthly excess return)/volatility of all dates -> actual; volatility is monthly std over all years
# use logit to get probs for all stocks, select top n highest probs to form 1/n portfolio

[1, -1, -1, 1]

In [1]:
import pandas as pd
import numpy as np
from scipy.optimize import minimize, approx_fprime
import torch
import matplotlib.pyplot as plt

from scipy.stats import mstats

In [5]:
link_table = pd.read_csv('permno-comnam.csv', index_col=0)
link_table.set_index('permno', inplace=True)

In [6]:
green_vars = pd.read_csv("green cleaned.csv", dtype={'ncusip': 'string'})
green_vars['ret_fwd_1'] = (green_vars.groupby('permno')['ret_excess'].shift(-1) )
green_vars = green_vars.dropna(subset=["ret_fwd_1"])

green_vars['datadate'] = pd.to_datetime(green_vars['DATE'], format='%Y%m%d')+pd.tseries.offsets.MonthEnd(0)
green_vars = green_vars.set_index('permno', drop=False)
green_vars = green_vars[['datadate', 'mve_m', 'ret_fwd_1']]

In [7]:
print(green_vars)

         datadate         mve_m  ret_fwd_1
permno
10006  1980-01-31  3.034208e+05  -0.067695
10006  1980-02-29  3.676485e+05  -0.184178
10006  1980-03-31  3.410715e+05  -0.040051
10006  1980-04-30  2.823806e+05   0.076577
10006  1980-05-31  2.746290e+05  -0.013676
...           ...           ...        ...
93436  2024-07-31  6.321554e+08  -0.082191
93436  2024-08-31  7.413801e+08   0.217942
93436  2024-09-30  6.840044e+08  -0.048925
93436  2024-10-31  8.390474e+08   0.377469
93436  2024-11-30  8.020335e+08   0.166308

[267678 rows x 3 columns]

In [6]:
green_vars[green_vars['datadate']=='2023-11-30'].sort_values(by='mve_m', ascending=False).head(10).loc[93436]

datadate     2023-11-30 00:00:00
mve_m                638454482.0
ret_fwd_1               0.030688
Name: 93436, dtype: object

## Value weighted

In [9]:
portfolio_returns = []
portfolio_turnover = []
prev_weights_dict = {}
prev_returns_dict = {}
prev_gross_return = 0.0
transaction_cost = 0.001  # 50 bps, same as your nodewise backtest

print_firms = True

# 3.5 is -39:-8
for date in sorted(green_vars['datadate'].unique())[-14:-8]:
    # Get data for this date
    date_data = green_vars[green_vars['datadate'] == date].copy()
    
    # Remove rows with missing returns or missing market values
    date_data = date_data.dropna(subset=['ret_fwd_1', 'mve_m'])
    
    if len(date_data) > 0 and date_data['mve_m'].sum() > 0:
        # Calculate weights (market value / total market value)
        weights = date_data['mve_m'] / date_data['mve_m'].sum()
        
        # Create weights dictionary
        weights_dict = weights.to_dict()
        returns_dict = date_data['ret_fwd_1'].to_dict()
        
        if print_firms:
            w = weights.to_frame(name='weight')
            merged = w.merge(link_table, on='permno', how='left').sort_values(by='weight', ascending=False).head(10)
            print(f"\n{date}")
            print(merged)
        
        # Calculate gross value-weighted return
        gross_return = (weights * date_data['ret_fwd_1']).sum()
        
        # Calculate transaction costs
        if len(prev_weights_dict) > 0:
            # Get all assets (current + previous)
            all_assets = set(weights_dict.keys()) | set(prev_weights_dict.keys())
            
            # Adjust previous weights: w+_{t,j} = w_{t,j} * (1 + r_{t,j}) / (1 + r_p,t)
            adjusted_prev = {}
            for asset in all_assets:
                prev_w = prev_weights_dict.get(asset, 0.0)
                
                if asset in prev_returns_dict and prev_gross_return > -0.99:
                    prev_r = prev_returns_dict[asset]
                    adjusted_prev[asset] = prev_w * (1 + prev_r) / (1 + prev_gross_return)
                else:
                    adjusted_prev[asset] = 0.0
            
            # Renormalize adjusted weights (only over current assets)
            adj_sum = sum(adjusted_prev.get(a, 0.0) for a in weights_dict.keys())
            if adj_sum > 1e-10:
                adjusted_prev_normalized = {k: adjusted_prev.get(k, 0.0)/adj_sum 
                                           for k in weights_dict.keys()}
            else:
                adjusted_prev_normalized = {k: 0.0 for k in weights_dict.keys()}
            
            # Turnover: sum over all assets
            turnover = sum(abs(weights_dict.get(a, 0.0) - adjusted_prev_normalized.get(a, 0.0)) 
                          for a in all_assets)
            
            # Transaction cost
            tc = transaction_cost * (1 + gross_return) * turnover
        else:
            # First period: full turnover
            turnover = sum(abs(w) for w in weights_dict.values())
            tc = transaction_cost * turnover
        
        # Net return
        net_return = gross_return - tc
        
        portfolio_returns.append(net_return)
        portfolio_turnover.append(turnover)
        
        # Update for next iteration
        prev_weights_dict = weights_dict.copy()
        prev_returns_dict = returns_dict.copy()
        prev_gross_return = gross_return

# Convert to array
portfolio_returns = np.array(portfolio_returns)
portfolio_turnover = np.array(portfolio_turnover)

# Calculate Sharpe ratio
mean_return = portfolio_returns.mean()
std_return = portfolio_returns.std()
sharpe_ratio = mean_return / std_return if std_return > 0 else 0
sharpe_ratio_annualized = sharpe_ratio * np.sqrt(12)

print(f"\n{'='*60}")
print("S&P 500 PERFORMANCE (WITH TRANSACTION COSTS)")
print(f"{'='*60}")
print(f"Mean Monthly Return:      {mean_return:.4f}")
print(f"Monthly Std Dev:          {std_return:.4f}")
print(f"Monthly Sharpe Ratio:     {sharpe_ratio:.4f}")
print(f"Annualized Sharpe Ratio:  {sharpe_ratio_annualized:.4f}")
print(f"Average Turnover:         {portfolio_turnover.mean():.4f}")
print(f"Number of periods:        {len(portfolio_returns)}")
print(f"{'='*60}")

2023-11-30 00:00:00
          weight                  comnam
permno
14593   0.081481               APPLE INC
10107   0.077093          MICROSOFT CORP
84788   0.042194          AMAZON COM INC
86580   0.030852             NVIDIA CORP
13407   0.020515      META PLATFORMS INC
93436   0.019587               TESLA INC
50876   0.016132          LILLY ELI & CO
92655   0.015219  UNITEDHEALTH GROUP INC
55976   0.013493             WALMART INC
11850   0.012869        EXXON MOBIL CORP

2023-12-31 00:00:00
          weight                  comnam
permno
14593   0.082900               APPLE INC
10107   0.079025          MICROSOFT CORP
84788   0.042364          AMAZON COM INC
86580   0.032417             NVIDIA CORP
93436   0.021416               TESLA INC
13407   0.020376      META PLATFORMS INC
50876   0.015745          LILLY ELI & CO
92655   0.014352  UNITEDHEALTH GROUP INC
47896   0.012662     JPMORGAN CHASE & CO
55976   0.011759             WALMART INC

2024-01-31 00:00:00
          weight                  comnam
permno
14593   0.080316               APPLE INC
10107   0.075412          MICROSOFT CORP
84788   0.041990          AMAZON COM INC
86580   0.033005             NVIDIA CORP
93436   0.021354               TESLA INC
13407   0.021117      META PLATFORMS INC
50876   0.014932          LILLY ELI & CO
47896   0.013269     JPMORGAN CHASE & CO
92655   0.013139  UNITEDHEALTH GROUP INC
55976   0.011452             WALMART INC

2024-02-29 00:00:00
          weight                  comnam
permno
10107   0.078500          MICROSOFT CORP
14593   0.075665               APPLE INC
84788   0.042838          AMAZON COM INC
86580   0.040285             NVIDIA CORP
13407   0.022808      META PLATFORMS INC
50876   0.016286          LILLY ELI & CO
93436   0.015850               TESLA INC
47896   0.013395     JPMORGAN CHASE & CO
92655   0.012577  UNITEDHEALTH GROUP INC
55976   0.011822             WALMART INC

2024-03-31 00:00:00
          weight                  comnam
permno
10107   0.077465          MICROSOFT CORP
14593   0.070347               APPLE INC
86580   0.049848             NVIDIA CORP
84788   0.046320          AMAZON COM INC
13407   0.027178      META PLATFORMS INC
50876   0.018049          LILLY ELI & CO
93436   0.016205               TESLA INC
47896   0.013507     JPMORGAN CHASE & CO
55976   0.011896             WALMART INC
92655   0.011469  UNITEDHEALTH GROUP INC

2024-04-30 00:00:00
          weight               comnam
permno
10107   0.076745       MICROSOFT CORP
14593   0.064552            APPLE INC
86580   0.054637          NVIDIA CORP
84788   0.046056       AMAZON COM INC
13407   0.026124   META PLATFORMS INC
50876   0.018154       LILLY ELI & CO
47896   0.014160  JPMORGAN CHASE & CO
93436   0.013759            TESLA INC
55976   0.011892          WALMART INC
11850   0.011320     EXXON MOBIL CORP

============================================================
S&P 500 PERFORMANCE (WITH TRANSACTION COSTS)
============================================================
Mean Monthly Return:      0.0199
Monthly Std Dev:          0.0330
Monthly Sharpe Ratio:     0.6021
Annualized Sharpe Ratio:  2.0857
Average Turnover:         0.2222
Number of periods:        6
============================================================

In [10]:
# Save value-weighted portfolio returns locally
pd.DataFrame({
    'portfolio_returns_vw': portfolio_returns
}).to_csv('portfolio_returns_vw 10 years 4o.csv', index=False)

print('Saved portfolio_returns to portfolio_returns 10 years 4o.csv')

Saved portfolio_returns to portfolio_returns 10 years 4o.csv

## Equal weighted

In [22]:
portfolio_returns_ew = []
portfolio_turnover_ew = []
prev_weights_dict = {}
prev_returns_dict = {}
prev_gross_return = 0.0
transaction_cost = 0.001  # 10 bps per unit of turnover; match the value-weighted setup if you prefer
print_firms = True

for date in sorted(green_vars['datadate'].unique())[-8-31:-8]:
    # Get data for this date
    date_data = green_vars[green_vars['datadate'] == date].copy()
    
    # Remove rows with missing returns or missing market values
    date_data = date_data.dropna(subset=['ret_fwd_1', 'mve_m'])
    
    if len(date_data) > 0:
        # Calculate equal weights (1/N for each firm)
        n_firms = len(date_data)
        weights = pd.Series(1 / n_firms, index=date_data.index)
        weights_dict = weights.to_dict()
        returns_dict = date_data['ret_fwd_1'].to_dict()
        
        if print_firms:
            w = weights.rename('weight').reset_index()
            merged = w.merge(link_table, on='permno', how='left').sort_values(by='weight', ascending=False).head(10)
            print(date)
            print(merged)
        
        # Equal-weighted gross return
        gross_return = date_data['ret_fwd_1'].mean()
        
        # Transaction costs based on turnover from prior period to current equal-weight target
        if len(prev_weights_dict) > 0:
            all_assets = set(weights_dict.keys()) | set(prev_weights_dict.keys())
            
            adjusted_prev = {}
            for asset in all_assets:
                prev_w = prev_weights_dict.get(asset, 0.0)
                
                if asset in prev_returns_dict and prev_gross_return > -0.99:
                    prev_r = prev_returns_dict[asset]
                    adjusted_prev[asset] = prev_w * (1 + prev_r) / (1 + prev_gross_return)
                else:
                    adjusted_prev[asset] = 0.0
            
            adj_sum = sum(adjusted_prev.get(a, 0.0) for a in weights_dict.keys())
            if adj_sum > 1e-10:
                adjusted_prev_normalized = {
                    k: adjusted_prev.get(k, 0.0) / adj_sum
                    for k in weights_dict.keys()
                }
            else:
                adjusted_prev_normalized = {k: 0.0 for k in weights_dict.keys()}
            
            turnover = sum(
                abs(weights_dict.get(a, 0.0) - adjusted_prev_normalized.get(a, 0.0))
                for a in all_assets
            )
            tc = transaction_cost * (1 + gross_return) * turnover
        else:
            # First period: full turnover into the initial portfolio
            turnover = sum(abs(w) for w in weights_dict.values())
            tc = transaction_cost * turnover
        
        net_return = gross_return - tc
        portfolio_returns_ew.append(net_return)
        portfolio_turnover_ew.append(turnover)
        
        # Update for next iteration
        prev_weights_dict = weights_dict.copy()
        prev_returns_dict = returns_dict.copy()
        prev_gross_return = gross_return

# Convert to array
portfolio_returns_ew = np.array(portfolio_returns_ew)
portfolio_turnover_ew = np.array(portfolio_turnover_ew)

# Calculate Sharpe ratio (assuming monthly returns)
mean_return = portfolio_returns_ew.mean()
std_return = portfolio_returns_ew.std()
sharpe_ratio = mean_return / std_return if std_return > 0 else 0

# Annualized Sharpe ratio (multiply by sqrt(12) for monthly data)
sharpe_ratio_annualized = sharpe_ratio * np.sqrt(12)

print(f"Mean Monthly Return: {mean_return:.4f}")
print(f"Monthly Std Dev: {std_return:.4f}")
print(f"Monthly Sharpe Ratio: {sharpe_ratio:.4f}")
print(f"Annualized Sharpe Ratio: {sharpe_ratio_annualized:.4f}")
print(f"Average Turnover: {portfolio_turnover_ew.mean():.4f}")
print(f"Number of periods: {len(portfolio_returns_ew)}")

2021-10-31 00:00:00
     permno    weight                  comnam
408   90071  0.002232        N R G ENERGY INC
409   90199  0.002232       C B R E GROUP INC
410   90215  0.002232          SALESFORCE INC
411   90248  0.002232       DOMINOS PIZZA INC
412   90386  0.002232           MOSAIC CO NEW
413   90454  0.002232   MARKETAXESS HLDGS INC
414   90455  0.002232  MONOLITHIC PWR SYS INC
415   90505  0.002232    LAS VEGAS SANDS CORP
400   89393  0.002232             NETFLIX INC
401   89508  0.002232              CARMAX INC
2021-11-30 00:00:00
     permno    weight                       comnam
443   93436  0.002252                    TESLA INC
0     10104  0.002252                  ORACLE CORP
1     10107  0.002252               MICROSOFT CORP
2     10138  0.002252       T ROWE PRICE GROUP INC
3     10145  0.002252  HONEYWELL INTERNATIONAL INC
4     10516  0.002252    ARCHER DANIELS MIDLAND CO
5     10696  0.002252                   FISERV INC
6     10909  0.002252                  CERNER CORP
7     11308  0.002252                 COCA COLA CO
8     11403  0.002252   CADENCE DESIGN SYSTEMS INC
2021-12-31 00:00:00
     permno    weight                       comnam
408   90038  0.002232                 ASSURANT INC
409   90071  0.002232             N R G ENERGY INC
410   90090  0.002232  SIGNATURE BANK NEW YORK N Y
411   90199  0.002232            C B R E GROUP INC
412   90215  0.002232               SALESFORCE INC
413   90248  0.002232            DOMINOS PIZZA INC
414   90386  0.002232                MOSAIC CO NEW
415   90454  0.002232        MARKETAXESS HLDGS INC
400   89269  0.002232             CENTENE CORP DEL
401   89393  0.002232                  NETFLIX INC
2022-01-31 00:00:00
     permno    weight                       comnam
445   93436  0.002242                    TESLA INC
0     10104  0.002242                  ORACLE CORP
1     10107  0.002242               MICROSOFT CORP
2     10138  0.002242       T ROWE PRICE GROUP INC
3     10145  0.002242  HONEYWELL INTERNATIONAL INC
4     10516  0.002242    ARCHER DANIELS MIDLAND CO
5     10696  0.002242                   FISERV INC
6     10909  0.002242                  CERNER CORP
7     11308  0.002242                 COCA COLA CO
8     11403  0.002242   CADENCE DESIGN SYSTEMS INC
2022-02-28 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     10909  0.002237                  CERNER CORP
7     11308  0.002237                 COCA COLA CO
8     11403  0.002237   CADENCE DESIGN SYSTEMS INC
2022-03-31 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     10909  0.002237                  CERNER CORP
7     11308  0.002237                 COCA COLA CO
8     11403  0.002237   CADENCE DESIGN SYSTEMS INC
2022-04-30 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     10909  0.002237                  CERNER CORP
7     11308  0.002237                 COCA COLA CO
8     11403  0.002237   CADENCE DESIGN SYSTEMS INC
2022-05-31 00:00:00
     permno    weight                       comnam
444   93436  0.002247                    TESLA INC
0     10104  0.002247                  ORACLE CORP
1     10107  0.002247               MICROSOFT CORP
2     10138  0.002247       T ROWE PRICE GROUP INC
3     10145  0.002247  HONEYWELL INTERNATIONAL INC
4     10516  0.002247    ARCHER DANIELS MIDLAND CO
5     10696  0.002247                   FISERV INC
6     11308  0.002247                 COCA COLA CO
7     11403  0.002247   CADENCE DESIGN SYSTEMS INC
8     11404  0.002247      CONSOLIDATED EDISON INC
2022-06-30 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     11308  0.002237                 COCA COLA CO
7     11403  0.002237   CADENCE DESIGN SYSTEMS INC
8     11404  0.002237      CONSOLIDATED EDISON INC
2022-07-31 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     11308  0.002237                 COCA COLA CO
7     11403  0.002237   CADENCE DESIGN SYSTEMS INC
8     11404  0.002237      CONSOLIDATED EDISON INC
2022-08-31 00:00:00
     permno    weight                       comnam
444   93436  0.002247                    TESLA INC
0     10104  0.002247                  ORACLE CORP
1     10107  0.002247               MICROSOFT CORP
2     10138  0.002247       T ROWE PRICE GROUP INC
3     10145  0.002247  HONEYWELL INTERNATIONAL INC
4     10516  0.002247    ARCHER DANIELS MIDLAND CO
5     10696  0.002247                   FISERV INC
6     11308  0.002247                 COCA COLA CO
7     11403  0.002247   CADENCE DESIGN SYSTEMS INC
8     11404  0.002247      CONSOLIDATED EDISON INC
2022-09-30 00:00:00
     permno    weight                       comnam
444   93436  0.002247                    TESLA INC
0     10104  0.002247                  ORACLE CORP
1     10107  0.002247               MICROSOFT CORP
2     10138  0.002247       T ROWE PRICE GROUP INC
3     10145  0.002247  HONEYWELL INTERNATIONAL INC
4     10516  0.002247    ARCHER DANIELS MIDLAND CO
5     10696  0.002247                   FISERV INC
6     11308  0.002247                 COCA COLA CO
7     11403  0.002247   CADENCE DESIGN SYSTEMS INC
8     11404  0.002247      CONSOLIDATED EDISON INC
2022-10-31 00:00:00
     permno    weight                       comnam
408   89866  0.002232                   L K Q CORP
409   90038  0.002232                 ASSURANT INC
410   90071  0.002232             N R G ENERGY INC
411   90090  0.002232  SIGNATURE BANK NEW YORK N Y
412   90199  0.002232            C B R E GROUP INC
413   90215  0.002232               SALESFORCE INC
414   90248  0.002232            DOMINOS PIZZA INC
415   90386  0.002232                MOSAIC CO NEW
400   89269  0.002232             CENTENE CORP DEL
401   89393  0.002232                  NETFLIX INC
2022-11-30 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     11308  0.002237                 COCA COLA CO
7     11403  0.002237   CADENCE DESIGN SYSTEMS INC
8     11404  0.002237      CONSOLIDATED EDISON INC
2022-12-31 00:00:00
     permno    weight                       comnam
408   90038  0.002232                 ASSURANT INC
409   90071  0.002232             N R G ENERGY INC
410   90090  0.002232  SIGNATURE BANK NEW YORK N Y
411   90199  0.002232            C B R E GROUP INC
412   90215  0.002232               SALESFORCE INC
413   90248  0.002232            DOMINOS PIZZA INC
414   90386  0.002232                MOSAIC CO NEW
415   90454  0.002232        MARKETAXESS HLDGS INC
400   89393  0.002232                  NETFLIX INC
401   89508  0.002232                   CARMAX INC
2023-01-31 00:00:00
     permno    weight                       comnam
408   90038  0.002232                 ASSURANT INC
409   90071  0.002232             N R G ENERGY INC
410   90090  0.002232  SIGNATURE BANK NEW YORK N Y
411   90199  0.002232            C B R E GROUP INC
412   90215  0.002232               SALESFORCE INC
413   90248  0.002232            DOMINOS PIZZA INC
414   90386  0.002232                MOSAIC CO NEW
415   90454  0.002232        MARKETAXESS HLDGS INC
400   89393  0.002232                  NETFLIX INC
401   89508  0.002232                   CARMAX INC
2023-02-28 00:00:00
     permno    weight                       comnam
444   93436  0.002247                    TESLA INC
0     10104  0.002247                  ORACLE CORP
1     10107  0.002247               MICROSOFT CORP
2     10138  0.002247       T ROWE PRICE GROUP INC
3     10145  0.002247  HONEYWELL INTERNATIONAL INC
4     10516  0.002247    ARCHER DANIELS MIDLAND CO
5     10696  0.002247                   FISERV INC
6     11308  0.002247                 COCA COLA CO
7     11403  0.002247   CADENCE DESIGN SYSTEMS INC
8     11404  0.002247      CONSOLIDATED EDISON INC
2023-03-31 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     11308  0.002237                 COCA COLA CO
7     11403  0.002237   CADENCE DESIGN SYSTEMS INC
8     11404  0.002237      CONSOLIDATED EDISON INC
2023-04-30 00:00:00
     permno    weight                       comnam
445   93436  0.002242                    TESLA INC
0     10104  0.002242                  ORACLE CORP
1     10107  0.002242               MICROSOFT CORP
2     10138  0.002242       T ROWE PRICE GROUP INC
3     10145  0.002242  HONEYWELL INTERNATIONAL INC
4     10516  0.002242    ARCHER DANIELS MIDLAND CO
5     10696  0.002242                   FISERV INC
6     11308  0.002242                 COCA COLA CO
7     11403  0.002242   CADENCE DESIGN SYSTEMS INC
8     11404  0.002242      CONSOLIDATED EDISON INC
2023-05-31 00:00:00
     permno    weight                       comnam
445   93436  0.002242                    TESLA INC
0     10104  0.002242                  ORACLE CORP
1     10107  0.002242               MICROSOFT CORP
2     10138  0.002242       T ROWE PRICE GROUP INC
3     10145  0.002242  HONEYWELL INTERNATIONAL INC
4     10516  0.002242    ARCHER DANIELS MIDLAND CO
5     10696  0.002242                   FISERV INC
6     11308  0.002242                 COCA COLA CO
7     11403  0.002242   CADENCE DESIGN SYSTEMS INC
8     11404  0.002242      CONSOLIDATED EDISON INC
2023-06-30 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     11308  0.002237                 COCA COLA CO
7     11403  0.002237   CADENCE DESIGN SYSTEMS INC
8     11404  0.002237      CONSOLIDATED EDISON INC
2023-07-31 00:00:00
     permno    weight                       comnam
445   93436  0.002242                    TESLA INC
0     10104  0.002242                  ORACLE CORP
1     10107  0.002242               MICROSOFT CORP
2     10138  0.002242       T ROWE PRICE GROUP INC
3     10145  0.002242  HONEYWELL INTERNATIONAL INC
4     10516  0.002242    ARCHER DANIELS MIDLAND CO
5     10696  0.002242                   FISERV INC
6     11308  0.002242                 COCA COLA CO
7     11403  0.002242   CADENCE DESIGN SYSTEMS INC
8     11404  0.002242      CONSOLIDATED EDISON INC
2023-08-31 00:00:00
     permno    weight                       comnam
445   93436  0.002242                    TESLA INC
0     10104  0.002242                  ORACLE CORP
1     10107  0.002242               MICROSOFT CORP
2     10138  0.002242       T ROWE PRICE GROUP INC
3     10145  0.002242  HONEYWELL INTERNATIONAL INC
4     10516  0.002242    ARCHER DANIELS MIDLAND CO
5     10696  0.002242                   FISERV INC
6     11308  0.002242                 COCA COLA CO
7     11403  0.002242   CADENCE DESIGN SYSTEMS INC
8     11404  0.002242      CONSOLIDATED EDISON INC
2023-09-30 00:00:00
     permno    weight                       comnam
443   93436  0.002252                    TESLA INC
0     10104  0.002252                  ORACLE CORP
1     10107  0.002252               MICROSOFT CORP
2     10138  0.002252       T ROWE PRICE GROUP INC
3     10145  0.002252  HONEYWELL INTERNATIONAL INC
4     10516  0.002252    ARCHER DANIELS MIDLAND CO
5     10696  0.002252                   FISERV INC
6     11308  0.002252                 COCA COLA CO
7     11403  0.002252   CADENCE DESIGN SYSTEMS INC
8     11404  0.002252      CONSOLIDATED EDISON INC
2023-10-31 00:00:00
     permno    weight                       comnam
445   93436  0.002242                    TESLA INC
0     10104  0.002242                  ORACLE CORP
1     10107  0.002242               MICROSOFT CORP
2     10138  0.002242       T ROWE PRICE GROUP INC
3     10145  0.002242  HONEYWELL INTERNATIONAL INC
4     10516  0.002242    ARCHER DANIELS MIDLAND CO
5     10696  0.002242                   FISERV INC
6     11308  0.002242                 COCA COLA CO
7     11403  0.002242   CADENCE DESIGN SYSTEMS INC
8     11404  0.002242      CONSOLIDATED EDISON INC
2023-11-30 00:00:00
     permno    weight                       comnam
443   93436  0.002252                    TESLA INC
0     10104  0.002252                  ORACLE CORP
1     10107  0.002252               MICROSOFT CORP
2     10138  0.002252       T ROWE PRICE GROUP INC
3     10145  0.002252  HONEYWELL INTERNATIONAL INC
4     10516  0.002252    ARCHER DANIELS MIDLAND CO
5     10696  0.002252                   FISERV INC
6     11308  0.002252                 COCA COLA CO
7     11403  0.002252   CADENCE DESIGN SYSTEMS INC
8     11404  0.002252      CONSOLIDATED EDISON INC
2023-12-31 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     11308  0.002237                 COCA COLA CO
7     11403  0.002237   CADENCE DESIGN SYSTEMS INC
8     11404  0.002237      CONSOLIDATED EDISON INC
2024-01-31 00:00:00
     permno    weight                       comnam
446   93436  0.002237                    TESLA INC
0     10104  0.002237                  ORACLE CORP
1     10107  0.002237               MICROSOFT CORP
2     10138  0.002237       T ROWE PRICE GROUP INC
3     10145  0.002237  HONEYWELL INTERNATIONAL INC
4     10516  0.002237    ARCHER DANIELS MIDLAND CO
5     10696  0.002237                   FISERV INC
6     11308  0.002237                 COCA COLA CO
7     11403  0.002237   CADENCE DESIGN SYSTEMS INC
8     11404  0.002237      CONSOLIDATED EDISON INC
2024-02-29 00:00:00
     permno    weight                       comnam
444   93436  0.002247                    TESLA INC
0     10104  0.002247                  ORACLE CORP
1     10107  0.002247               MICROSOFT CORP
2     10138  0.002247       T ROWE PRICE GROUP INC
3     10145  0.002247  HONEYWELL INTERNATIONAL INC
4     10516  0.002247    ARCHER DANIELS MIDLAND CO
5     10696  0.002247                   FISERV INC
6     11308  0.002247                 COCA COLA CO
7     11403  0.002247   CADENCE DESIGN SYSTEMS INC
8     11404  0.002247      CONSOLIDATED EDISON INC
2024-03-31 00:00:00
     permno    weight                       comnam
444   93436  0.002247                    TESLA INC
0     10104  0.002247                  ORACLE CORP
1     10107  0.002247               MICROSOFT CORP
2     10138  0.002247       T ROWE PRICE GROUP INC
3     10145  0.002247  HONEYWELL INTERNATIONAL INC
4     10516  0.002247    ARCHER DANIELS MIDLAND CO
5     10696  0.002247                   FISERV INC
6     11308  0.002247                 COCA COLA CO
7     11403  0.002247   CADENCE DESIGN SYSTEMS INC
8     11404  0.002247      CONSOLIDATED EDISON INC
2024-04-30 00:00:00
     permno    weight                       comnam
443   93436  0.002252                    TESLA INC
0     10104  0.002252                  ORACLE CORP
1     10107  0.002252               MICROSOFT CORP
2     10138  0.002252       T ROWE PRICE GROUP INC
3     10145  0.002252  HONEYWELL INTERNATIONAL INC
4     10516  0.002252    ARCHER DANIELS MIDLAND CO
5     10696  0.002252                   FISERV INC
6     11308  0.002252                 COCA COLA CO
7     11403  0.002252   CADENCE DESIGN SYSTEMS INC
8     11404  0.002252      CONSOLIDATED EDISON INC
Mean Monthly Return: 0.0026
Monthly Std Dev: 0.0545
Monthly Sharpe Ratio: 0.0471
Annualized Sharpe Ratio: 0.1633
Average Turnover: 0.0884
Number of periods: 31

In [19]:
# Save equal-weighted portfolio returns locally
pd.DataFrame({
    'portfolio_returns_ew': portfolio_returns_ew
}).to_csv('portfolio_returns_ew 10 years 3.5.csv', index=False)

print('Saved portfolio_returns_ew to portfolio_returns_ew 10 years 3.5.csv')

Saved portfolio_returns_ew to portfolio_returns_ew 10 years 3.5.csv

# Daily Data

In [3]:
df = pd.read_csv('./Paper revisions/filtered_daily_data_w_ticker.csv')
df['ret_fwd_1'] = df.groupby('permno')['ret_excess'].shift(-1)
df = df.rename(columns={'date': 'datadate'})

In [4]:
df

        permno    datadate  ret_excess ticker  ret_fwd_1
0        10104  2023-04-21    0.003194   ORCL   0.002868
1        10104  2023-04-24    0.002868   ORCL  -0.014639
2        10104  2023-04-25   -0.014639   ORCL  -0.003901
3        10104  2023-04-26   -0.003901   ORCL   0.014013
4        10104  2023-04-27    0.014013   ORCL  -0.003547
...        ...         ...         ...    ...        ...
166391   93436  2023-06-30    0.016393   TSLA   0.068734
166392   93436  2023-07-03    0.068734   TSLA  -0.029156
166393   93436  2024-04-10   -0.029156   TSLA   0.016325
166394   93436  2024-04-11    0.016325   TSLA  -0.020542
166395   93436  2024-04-12   -0.020542   TSLA        NaN

[166396 rows x 5 columns]

In [8]:
# 1. Ensure 'datadate' is a datetime object in both dataframes
df['datadate'] = pd.to_datetime(df['datadate'])
green_vars['datadate'] = pd.to_datetime(green_vars['datadate'])

# 2. Reset index on green_vars if 'permno' is currently set as the index
if 'permno' not in green_vars.columns:
    green_vars = green_vars.reset_index()

# 3. Create the 'year_month' merge key
# For daily data, extract the current month
df['year_month'] = df['datadate'].dt.to_period('M')

# For monthly data, shift the month FORWARD by 1. 
# This ensures that end-of-January mve_m (Month 1) becomes Month 2, 
# perfectly aligning the previous month's market cap with the current month's daily returns.
green_vars['year_month'] = green_vars['datadate'].dt.to_period('M') + 1

# 4. Merge the dataframes
# Subsetting green_vars avoids bringing in duplicate columns (like ret_fwd_1)
merged_df = pd.merge(
    df,
    green_vars[['permno', 'year_month', 'mve_m']],
    on=['permno', 'year_month'],
    how='left'
)

# Clean up the helper column
merged_df = merged_df.drop(columns=['year_month'])

In [14]:
merged_df = merged_df.set_index('permno')
merged_df

         datadate  ret_excess ticker  ret_fwd_1         mve_m
permno
10104  2023-04-21    0.003194   ORCL   0.002868  2.356525e+08
10104  2023-04-24    0.002868   ORCL  -0.014639  2.356525e+08
10104  2023-04-25   -0.014639   ORCL  -0.003901  2.356525e+08
10104  2023-04-26   -0.003901   ORCL   0.014013  2.356525e+08
10104  2023-04-27    0.014013   ORCL  -0.003547  2.356525e+08
...           ...         ...    ...        ...           ...
93436  2023-06-30    0.016393   TSLA   0.068734  5.207812e+08
93436  2023-07-03    0.068734   TSLA  -0.029156  6.463569e+08
93436  2024-04-10   -0.029156   TSLA   0.016325  6.429454e+08
93436  2024-04-11    0.016325   TSLA  -0.020542  6.429454e+08
93436  2024-04-12   -0.020542   TSLA        NaN  6.429454e+08

[166396 rows x 5 columns]

In [19]:
portfolio_returns = []
portfolio_turnover = []
prev_weights_dict = {}
prev_returns_dict = {}
prev_gross_return = 0.0
transaction_cost = 0.001  # 50 bps, same as your nodewise backtest

print_firms = True

# 3.5 is -39:-8
for date in sorted(merged_df['datadate'].unique())[-62:]:
    # Get data for this date
    date_data = merged_df[merged_df['datadate'] == date].copy()
    
    # Remove rows with missing returns or missing market values
    date_data = date_data.dropna(subset=['ret_fwd_1', 'mve_m'])
    
    if len(date_data) > 0 and date_data['mve_m'].sum() > 0:
        # Calculate weights (market value / total market value)
        weights = date_data['mve_m'] / date_data['mve_m'].sum()
        
        # Create weights dictionary
        weights_dict = weights.to_dict()
        returns_dict = date_data['ret_fwd_1'].to_dict()
        
        if print_firms:
            w = weights.to_frame(name='weight')
            merged = w.merge(link_table, on='permno', how='left').sort_values(by='weight', ascending=False).head(10)
            print(f"\n{date}")
            print(merged)
        
        # Calculate gross value-weighted return
        gross_return = (weights * date_data['ret_fwd_1']).sum()
        
        # Calculate transaction costs
        if len(prev_weights_dict) > 0:
            # Get all assets (current + previous)
            all_assets = set(weights_dict.keys()) | set(prev_weights_dict.keys())
            
            # Adjust previous weights: w+_{t,j} = w_{t,j} * (1 + r_{t,j}) / (1 + r_p,t)
            adjusted_prev = {}
            for asset in all_assets:
                prev_w = prev_weights_dict.get(asset, 0.0)
                
                if asset in prev_returns_dict and prev_gross_return > -0.99:
                    prev_r = prev_returns_dict[asset]
                    adjusted_prev[asset] = prev_w * (1 + prev_r) / (1 + prev_gross_return)
                else:
                    adjusted_prev[asset] = 0.0
            
            # Renormalize adjusted weights (only over current assets)
            adj_sum = sum(adjusted_prev.get(a, 0.0) for a in weights_dict.keys())
            if adj_sum > 1e-10:
                adjusted_prev_normalized = {k: adjusted_prev.get(k, 0.0)/adj_sum 
                                           for k in weights_dict.keys()}
            else:
                adjusted_prev_normalized = {k: 0.0 for k in weights_dict.keys()}
            
            # Turnover: sum over all assets
            turnover = sum(abs(weights_dict.get(a, 0.0) - adjusted_prev_normalized.get(a, 0.0)) 
                          for a in all_assets)
            
            # Transaction cost
            tc = transaction_cost * (1 + gross_return) * turnover
        else:
            # First period: full turnover
            turnover = sum(abs(w) for w in weights_dict.values())
            tc = transaction_cost * turnover
        
        # Net return
        net_return = gross_return - tc
        
        portfolio_returns.append(net_return)
        portfolio_turnover.append(turnover)
        
        # Update for next iteration
        prev_weights_dict = weights_dict.copy()
        prev_returns_dict = returns_dict.copy()
        prev_gross_return = gross_return

# Convert to array
portfolio_returns = np.array(portfolio_returns)
portfolio_turnover = np.array(portfolio_turnover)

# Calculate Sharpe ratio
mean_return = portfolio_returns.mean()
std_return = portfolio_returns.std()
sharpe_ratio = mean_return / std_return if std_return > 0 else 0
sharpe_ratio_annualized = sharpe_ratio * np.sqrt(252)

print(f"\n{'='*60}")
print("S&P 500 PERFORMANCE (WITH TRANSACTION COSTS)")
print(f"{'='*60}")
print(f"Mean Daily Return:      {mean_return:.4f}")
print(f"Daily Std Dev:          {std_return:.4f}")
print(f"Daily Sharpe Ratio:     {sharpe_ratio:.4f}")
print(f"Annualized Sharpe Ratio:  {sharpe_ratio_annualized:.4f}")
print(f"Average Turnover:         {portfolio_turnover.mean():.4f}")
print(f"Number of periods:        {len(portfolio_returns)}")
print(f"{'='*60}")

2024-02-01 00:00:00
          weight                  comnam
permno
14593   0.080316               APPLE INC
10107   0.075412          MICROSOFT CORP
84788   0.041990          AMAZON COM INC
86580   0.033005             NVIDIA CORP
93436   0.021354               TESLA INC
13407   0.021117      META PLATFORMS INC
50876   0.014932          LILLY ELI & CO
47896   0.013269     JPMORGAN CHASE & CO
92655   0.013139  UNITEDHEALTH GROUP INC
55976   0.011452             WALMART INC

2024-02-02 00:00:00
          weight                  comnam
permno
14593   0.081029               APPLE INC
10107   0.076082          MICROSOFT CORP
84788   0.042363          AMAZON COM INC
86580   0.033298             NVIDIA CORP
93436   0.021544               TESLA INC
13407   0.021304      META PLATFORMS INC
50876   0.015064          LILLY ELI & CO
47896   0.013387     JPMORGAN CHASE & CO
92655   0.013256  UNITEDHEALTH GROUP INC
55976   0.011554             WALMART INC

2024-02-05 00:00:00
          weight                  comnam
permno
14593   0.080759               APPLE INC
10107   0.075828          MICROSOFT CORP
84788   0.042221          AMAZON COM INC
86580   0.033187             NVIDIA CORP
93436   0.021472               TESLA INC
13407   0.021233      META PLATFORMS INC
50876   0.015014          LILLY ELI & CO
47896   0.013342     JPMORGAN CHASE & CO
92655   0.013212  UNITEDHEALTH GROUP INC
55976   0.011516             WALMART INC

2024-02-06 00:00:00
          weight                  comnam
permno
14593   0.081325               APPLE INC
10107   0.076360          MICROSOFT CORP
84788   0.042517          AMAZON COM INC
86580   0.033420             NVIDIA CORP
93436   0.021623               TESLA INC
13407   0.021382      META PLATFORMS INC
50876   0.015119          LILLY ELI & CO
47896   0.013436     JPMORGAN CHASE & CO
92655   0.013304  UNITEDHEALTH GROUP INC
55976   0.011596             WALMART INC

2024-02-07 00:00:00
          weight                  comnam
permno
14593   0.080600               APPLE INC
10107   0.075679          MICROSOFT CORP
84788   0.042138          AMAZON COM INC
86580   0.033122             NVIDIA CORP
93436   0.021430               TESLA INC
13407   0.021192      META PLATFORMS INC
50876   0.014984          LILLY ELI & CO
47896   0.013316     JPMORGAN CHASE & CO
92655   0.013186  UNITEDHEALTH GROUP INC
55976   0.011493             WALMART INC

2024-02-08 00:00:00
          weight                  comnam
permno
14593   0.080535               APPLE INC
10107   0.075618          MICROSOFT CORP
84788   0.042105          AMAZON COM INC
86580   0.033095             NVIDIA CORP
93436   0.021413               TESLA INC
13407   0.021175      META PLATFORMS INC
50876   0.014972          LILLY ELI & CO
47896   0.013305     JPMORGAN CHASE & CO
92655   0.013175  UNITEDHEALTH GROUP INC
55976   0.011484             WALMART INC

2024-02-09 00:00:00
          weight                  comnam
permno
14593   0.080316               APPLE INC
10107   0.075412          MICROSOFT CORP
84788   0.041990          AMAZON COM INC
86580   0.033005             NVIDIA CORP
93436   0.021354               TESLA INC
13407   0.021117      META PLATFORMS INC
50876   0.014932          LILLY ELI & CO
47896   0.013269     JPMORGAN CHASE & CO
92655   0.013139  UNITEDHEALTH GROUP INC
55976   0.011452             WALMART INC

2024-02-12 00:00:00
          weight                  comnam
permno
14593   0.081017               APPLE INC
10107   0.076071          MICROSOFT CORP
84788   0.042356          AMAZON COM INC
86580   0.033293             NVIDIA CORP
93436   0.021541               TESLA INC
13407   0.021301      META PLATFORMS INC
50876   0.015062          LILLY ELI & CO
47896   0.013385     JPMORGAN CHASE & CO
92655   0.013254  UNITEDHEALTH GROUP INC
55976   0.011552             WALMART INC

2024-02-13 00:00:00
          weight                  comnam
permno
14593   0.080673               APPLE INC
10107   0.075748          MICROSOFT CORP
84788   0.042177          AMAZON COM INC
86580   0.033152             NVIDIA CORP
93436   0.021449               TESLA INC
13407   0.021211      META PLATFORMS INC
50876   0.014998          LILLY ELI & CO
47896   0.013328     JPMORGAN CHASE & CO
92655   0.013198  UNITEDHEALTH GROUP INC
55976   0.011503             WALMART INC

2024-02-14 00:00:00
          weight                  comnam
permno
14593   0.080500               APPLE INC
10107   0.075585          MICROSOFT CORP
84788   0.042086          AMAZON COM INC
86580   0.033081             NVIDIA CORP
93436   0.021403               TESLA INC
13407   0.021165      META PLATFORMS INC
50876   0.014966          LILLY ELI & CO
47896   0.013300     JPMORGAN CHASE & CO
92655   0.013169  UNITEDHEALTH GROUP INC
55976   0.011479             WALMART INC

2024-02-15 00:00:00
          weight                  comnam
permno
14593   0.080338               APPLE INC
10107   0.075433          MICROSOFT CORP
84788   0.042001          AMAZON COM INC
86580   0.033014             NVIDIA CORP
93436   0.021360               TESLA INC
13407   0.021123      META PLATFORMS INC
50876   0.014936          LILLY ELI & CO
47896   0.013273     JPMORGAN CHASE & CO
92655   0.013143  UNITEDHEALTH GROUP INC
55976   0.011456             WALMART INC

2024-02-16 00:00:00
          weight                  comnam
permno
14593   0.081247               APPLE INC
10107   0.076286          MICROSOFT CORP
84788   0.042476          AMAZON COM INC
86580   0.033388             NVIDIA CORP
93436   0.021602               TESLA INC
13407   0.021362      META PLATFORMS INC
50876   0.015104          LILLY ELI & CO
47896   0.013423     JPMORGAN CHASE & CO
92655   0.013291  UNITEDHEALTH GROUP INC
92611   0.011246                VISA INC

2024-02-20 00:00:00
          weight                  comnam
permno
14593   0.080682               APPLE INC
10107   0.075756          MICROSOFT CORP
84788   0.042181          AMAZON COM INC
86580   0.033156             NVIDIA CORP
93436   0.021452               TESLA INC
13407   0.021213      META PLATFORMS INC
50876   0.015000          LILLY ELI & CO
47896   0.013330     JPMORGAN CHASE & CO
92655   0.013199  UNITEDHEALTH GROUP INC
55976   0.011505             WALMART INC

2024-02-21 00:00:00
          weight                  comnam
permno
14593   0.080413               APPLE INC
10107   0.075503          MICROSOFT CORP
84788   0.042040          AMAZON COM INC
86580   0.033045             NVIDIA CORP
93436   0.021380               TESLA INC
13407   0.021142      META PLATFORMS INC
50876   0.014949          LILLY ELI & CO
47896   0.013285     JPMORGAN CHASE & CO
92655   0.013155  UNITEDHEALTH GROUP INC
55976   0.011466             WALMART INC

2024-02-22 00:00:00
          weight                  comnam
permno
14593   0.080599               APPLE INC
10107   0.075679          MICROSOFT CORP
84788   0.042138          AMAZON COM INC
86580   0.033122             NVIDIA CORP
93436   0.021430               TESLA INC
13407   0.021191      META PLATFORMS INC
50876   0.014984          LILLY ELI & CO
47896   0.013316     JPMORGAN CHASE & CO
92655   0.013186  UNITEDHEALTH GROUP INC
55976   0.011493             WALMART INC

2024-02-23 00:00:00
          weight                  comnam
permno
14593   0.080316               APPLE INC
10107   0.075412          MICROSOFT CORP
84788   0.041990          AMAZON COM INC
86580   0.033005             NVIDIA CORP
93436   0.021354               TESLA INC
13407   0.021117      META PLATFORMS INC
50876   0.014932          LILLY ELI & CO
47896   0.013269     JPMORGAN CHASE & CO
92655   0.013139  UNITEDHEALTH GROUP INC
55976   0.011452             WALMART INC

2024-02-26 00:00:00
          weight                  comnam
permno
14593   0.080476               APPLE INC
10107   0.075562          MICROSOFT CORP
84788   0.042073          AMAZON COM INC
86580   0.033071             NVIDIA CORP
93436   0.021397               TESLA INC
13407   0.021159      META PLATFORMS INC
50876   0.014961          LILLY ELI & CO
47896   0.013295     JPMORGAN CHASE & CO
92655   0.013165  UNITEDHEALTH GROUP INC
55976   0.011475             WALMART INC

2024-02-27 00:00:00
          weight                  comnam
permno
14593   0.080354               APPLE INC
10107   0.075448          MICROSOFT CORP
84788   0.042010          AMAZON COM INC
86580   0.033021             NVIDIA CORP
93436   0.021365               TESLA INC
13407   0.021127      META PLATFORMS INC
50876   0.014939          LILLY ELI & CO
47896   0.013275     JPMORGAN CHASE & CO
92655   0.013145  UNITEDHEALTH GROUP INC
55976   0.011458             WALMART INC

2024-02-28 00:00:00
          weight                  comnam
permno
14593   0.080409               APPLE INC
10107   0.075500          MICROSOFT CORP
84788   0.042038          AMAZON COM INC
86580   0.033043             NVIDIA CORP
93436   0.021379               TESLA INC
13407   0.021141      META PLATFORMS INC
50876   0.014949          LILLY ELI & CO
47896   0.013284     JPMORGAN CHASE & CO
92655   0.013154  UNITEDHEALTH GROUP INC
55976   0.011466             WALMART INC

2024-02-29 00:00:00
          weight                  comnam
permno
14593   0.080370               APPLE INC
10107   0.075463          MICROSOFT CORP
84788   0.042018          AMAZON COM INC
86580   0.033028             NVIDIA CORP
93436   0.021369               TESLA INC
13407   0.021131      META PLATFORMS INC
50876   0.014942          LILLY ELI & CO
47896   0.013278     JPMORGAN CHASE & CO
92655   0.013148  UNITEDHEALTH GROUP INC
55976   0.011460             WALMART INC

2024-03-01 00:00:00
          weight                  comnam
permno
10107   0.078500          MICROSOFT CORP
14593   0.075665               APPLE INC
84788   0.042838          AMAZON COM INC
86580   0.040285             NVIDIA CORP
13407   0.022808      META PLATFORMS INC
50876   0.016286          LILLY ELI & CO
93436   0.015850               TESLA INC
47896   0.013395     JPMORGAN CHASE & CO
92655   0.012577  UNITEDHEALTH GROUP INC
55976   0.011822             WALMART INC

2024-03-04 00:00:00
          weight                  comnam
permno
10107   0.078725          MICROSOFT CORP
14593   0.075881               APPLE INC
84788   0.042960          AMAZON COM INC
86580   0.040400             NVIDIA CORP
13407   0.022873      META PLATFORMS INC
50876   0.016332          LILLY ELI & CO
93436   0.015895               TESLA INC
47896   0.013433     JPMORGAN CHASE & CO
92655   0.012613  UNITEDHEALTH GROUP INC
55976   0.011856             WALMART INC

2024-03-05 00:00:00
          weight                  comnam
permno
10107   0.078671          MICROSOFT CORP
14593   0.075830               APPLE INC
84788   0.042932          AMAZON COM INC
86580   0.040372             NVIDIA CORP
13407   0.022858      META PLATFORMS INC
50876   0.016321          LILLY ELI & CO
93436   0.015885               TESLA INC
47896   0.013424     JPMORGAN CHASE & CO
92655   0.012605  UNITEDHEALTH GROUP INC
55976   0.011848             WALMART INC

2024-03-06 00:00:00
          weight                  comnam
permno
10107   0.078514          MICROSOFT CORP
14593   0.075678               APPLE INC
84788   0.042845          AMAZON COM INC
86580   0.040291             NVIDIA CORP
13407   0.022812      META PLATFORMS INC
50876   0.016289          LILLY ELI & CO
93436   0.015853               TESLA INC
47896   0.013397     JPMORGAN CHASE & CO
92655   0.012579  UNITEDHEALTH GROUP INC
55976   0.011824             WALMART INC

2024-03-07 00:00:00
          weight                  comnam
permno
10107   0.078907          MICROSOFT CORP
14593   0.076057               APPLE INC
84788   0.043060          AMAZON COM INC
86580   0.040493             NVIDIA CORP
13407   0.022926      META PLATFORMS INC
50876   0.016370          LILLY ELI & CO
93436   0.015932               TESLA INC
47896   0.013464     JPMORGAN CHASE & CO
92655   0.012643  UNITEDHEALTH GROUP INC
55976   0.011883             WALMART INC

2024-03-08 00:00:00
          weight                  comnam
permno
10107   0.080619          MICROSOFT CORP
14593   0.077707               APPLE INC
84788   0.043994          AMAZON COM INC
86580   0.041372             NVIDIA CORP
13407   0.023423      META PLATFORMS INC
93436   0.016278               TESLA INC
47896   0.013756     JPMORGAN CHASE & CO
92655   0.012917  UNITEDHEALTH GROUP INC
55976   0.012141             WALMART INC
92611   0.011794                VISA INC

2024-03-11 00:00:00
          weight                  comnam
permno
10107   0.078713          MICROSOFT CORP
14593   0.075870               APPLE INC
84788   0.042954          AMAZON COM INC
86580   0.040394             NVIDIA CORP
13407   0.022870      META PLATFORMS INC
50876   0.016330          LILLY ELI & CO
93436   0.015893               TESLA INC
47896   0.013431     JPMORGAN CHASE & CO
92655   0.012611  UNITEDHEALTH GROUP INC
55976   0.011854             WALMART INC

2024-03-12 00:00:00
          weight                  comnam
permno
10107   0.078500          MICROSOFT CORP
14593   0.075665               APPLE INC
84788   0.042838          AMAZON COM INC
86580   0.040285             NVIDIA CORP
13407   0.022808      META PLATFORMS INC
50876   0.016286          LILLY ELI & CO
93436   0.015850               TESLA INC
47896   0.013395     JPMORGAN CHASE & CO
92655   0.012577  UNITEDHEALTH GROUP INC
55976   0.011822             WALMART INC

2024-03-13 00:00:00
          weight                  comnam
permno
10107   0.078544          MICROSOFT CORP
14593   0.075707               APPLE INC
84788   0.042862          AMAZON COM INC
86580   0.040307             NVIDIA CORP
13407   0.022821      META PLATFORMS INC
50876   0.016295          LILLY ELI & CO
93436   0.015859               TESLA INC
47896   0.013402     JPMORGAN CHASE & CO
92655   0.012584  UNITEDHEALTH GROUP INC
55976   0.011829             WALMART INC

2024-03-14 00:00:00
          weight                  comnam
permno
10107   0.078668          MICROSOFT CORP
14593   0.075827               APPLE INC
84788   0.042930          AMAZON COM INC
86580   0.040371             NVIDIA CORP
13407   0.022857      META PLATFORMS INC
50876   0.016321          LILLY ELI & CO
93436   0.015884               TESLA INC
47896   0.013423     JPMORGAN CHASE & CO
92655   0.012604  UNITEDHEALTH GROUP INC
55976   0.011847             WALMART INC

2024-03-15 00:00:00
          weight                  comnam
permno
10107   0.078500          MICROSOFT CORP
14593   0.075665               APPLE INC
84788   0.042838          AMAZON COM INC
86580   0.040285             NVIDIA CORP
13407   0.022808      META PLATFORMS INC
50876   0.016286          LILLY ELI & CO
93436   0.015850               TESLA INC
47896   0.013395     JPMORGAN CHASE & CO
92655   0.012577  UNITEDHEALTH GROUP INC
55976   0.011822             WALMART INC

2024-03-18 00:00:00
          weight                  comnam
permno
10107   0.078500          MICROSOFT CORP
14593   0.075665               APPLE INC
84788   0.042838          AMAZON COM INC
86580   0.040285             NVIDIA CORP
13407   0.022808      META PLATFORMS INC
50876   0.016286          LILLY ELI & CO
93436   0.015850               TESLA INC
47896   0.013395     JPMORGAN CHASE & CO
92655   0.012577  UNITEDHEALTH GROUP INC
55976   0.011822             WALMART INC

2024-03-19 00:00:00
          weight                  comnam
permno
10107   0.078924          MICROSOFT CORP
14593   0.076073               APPLE INC
84788   0.043069          AMAZON COM INC
86580   0.040502             NVIDIA CORP
13407   0.022931      META PLATFORMS INC
50876   0.016374          LILLY ELI & CO
93436   0.015935               TESLA INC
47896   0.013467     JPMORGAN CHASE & CO
92655   0.012645  UNITEDHEALTH GROUP INC
55976   0.011886             WALMART INC

2024-03-20 00:00:00
          weight                  comnam
permno
10107   0.079009          MICROSOFT CORP
14593   0.076155               APPLE INC
84788   0.043116          AMAZON COM INC
86580   0.040546             NVIDIA CORP
13407   0.022956      META PLATFORMS INC
50876   0.016391          LILLY ELI & CO
93436   0.015953               TESLA INC
47896   0.013481     JPMORGAN CHASE & CO
92655   0.012659  UNITEDHEALTH GROUP INC
55976   0.011899             WALMART INC

2024-03-21 00:00:00
          weight                  comnam
permno
10107   0.078563          MICROSOFT CORP
14593   0.075725               APPLE INC
84788   0.042872          AMAZON COM INC
86580   0.040317             NVIDIA CORP
13407   0.022826      META PLATFORMS INC
50876   0.016299          LILLY ELI & CO
93436   0.015863               TESLA INC
47896   0.013405     JPMORGAN CHASE & CO
92655   0.012587  UNITEDHEALTH GROUP INC
55976   0.011831             WALMART INC

2024-03-22 00:00:00
          weight                  comnam
permno
10107   0.078521          MICROSOFT CORP
14593   0.075685               APPLE INC
84788   0.042850          AMAZON COM INC
86580   0.040295             NVIDIA CORP
13407   0.022814      META PLATFORMS INC
50876   0.016290          LILLY ELI & CO
93436   0.015854               TESLA INC
47896   0.013398     JPMORGAN CHASE & CO
92655   0.012581  UNITEDHEALTH GROUP INC
55976   0.011825             WALMART INC

2024-03-25 00:00:00
          weight                  comnam
permno
10107   0.078533          MICROSOFT CORP
14593   0.075696               APPLE INC
84788   0.042856          AMAZON COM INC
86580   0.040301             NVIDIA CORP
13407   0.022817      META PLATFORMS INC
50876   0.016293          LILLY ELI & CO
93436   0.015857               TESLA INC
47896   0.013400     JPMORGAN CHASE & CO
92655   0.012583  UNITEDHEALTH GROUP INC
55976   0.011827             WALMART INC

2024-03-26 00:00:00
          weight                  comnam
permno
10107   0.078592          MICROSOFT CORP
14593   0.075753               APPLE INC
84788   0.042888          AMAZON COM INC
86580   0.040332             NVIDIA CORP
13407   0.022835      META PLATFORMS INC
50876   0.016305          LILLY ELI & CO
93436   0.015868               TESLA INC
47896   0.013410     JPMORGAN CHASE & CO
92655   0.012592  UNITEDHEALTH GROUP INC
55976   0.011836             WALMART INC

2024-03-27 00:00:00
          weight                  comnam
permno
10107   0.078700          MICROSOFT CORP
14593   0.075857               APPLE INC
84788   0.042947          AMAZON COM INC
86580   0.040387             NVIDIA CORP
13407   0.022866      META PLATFORMS INC
50876   0.016327          LILLY ELI & CO
93436   0.015890               TESLA INC
47896   0.013429     JPMORGAN CHASE & CO
92655   0.012609  UNITEDHEALTH GROUP INC
55976   0.011852             WALMART INC

2024-03-28 00:00:00
          weight                  comnam
permno
10107   0.078558          MICROSOFT CORP
14593   0.075720               APPLE INC
84788   0.042870          AMAZON COM INC
86580   0.040314             NVIDIA CORP
13407   0.022825      META PLATFORMS INC
50876   0.016298          LILLY ELI & CO
93436   0.015862               TESLA INC
47896   0.013404     JPMORGAN CHASE & CO
92655   0.012587  UNITEDHEALTH GROUP INC
55976   0.011831             WALMART INC

2024-04-01 00:00:00
          weight                  comnam
permno
10107   0.077926          MICROSOFT CORP
14593   0.070766               APPLE INC
86580   0.050145             NVIDIA CORP
84788   0.046596          AMAZON COM INC
13407   0.027339      META PLATFORMS INC
50876   0.018156          LILLY ELI & CO
93436   0.016301               TESLA INC
47896   0.013588     JPMORGAN CHASE & CO
55976   0.011966             WALMART INC
92655   0.011538  UNITEDHEALTH GROUP INC

2024-04-02 00:00:00
          weight                  comnam
permno
10107   0.077465          MICROSOFT CORP
14593   0.070347               APPLE INC
86580   0.049848             NVIDIA CORP
84788   0.046320          AMAZON COM INC
13407   0.027178      META PLATFORMS INC
50876   0.018049          LILLY ELI & CO
93436   0.016205               TESLA INC